### ISSUE TITLE
《太平洋学报》格式

### ISSUE THREAD

**Issue by vw911** [EdwardSaidZhou/CSL-Chinese-IR-CSSCI-Journals#10]
大佬您好，

《太平洋学报》的最新引文格式有很多差异，请问有空调整一下吗？谢谢，辛苦啦！

以下来自《太平洋学报》官网：
    1. 中文脚注格式
    （1）文章格式：作者名：“文章名”，杂志名，刊期，页码。
例如：张文木：“中国地缘政治的特点及其变动规律（上）”，《太平洋学报》，2013年第1期，第1页。
    （2）书籍格式：作者名+著：《书名》，出版社，出版年份，页码。
                 [国籍]作者名+着，译者名+译：《书名》，出版社，出版年份，页码。
例如：郑海麟著：《钓鱼岛列屿之历史与法理研究》（最新增订本），海洋出版社，2014年版，第6页。
[美]戴维·梅森着，倪乐雄、孙云峰译：《美国世纪的终结》，上海辞书出版社，2009年版，第179页。
    （3）网站资料：作者名：“标题”，网站名，日期，网址。
例如：杨光：“外媒热议中国海军索马里护航”，新华网，2012年12月22日，http://news.xinhuanet.com/mil/2008-12/22/content10542679.htm。
    （4）博士论文格式：作者名：《文章名》，某大学博士论文，年份，页码。
例如：xxx:《xxxxxxxxxxxx》,北京大学博士论文，2012年，第56页。
 
    2. 英文脚注格式
    （1）报纸文章格式：作者名，文章名（正体+引号），报纸名（正体），日期。
例如：Walter Lohman, “Shaping U.S.'s Future in the Indo-Pacific ” ,The Washington Times, April 20, 2011.
    （2）期刊文章格式：作者名，文章名（正体+引号），杂志名（斜体），刊期，页码。
例如：Michael J. Green and Andrew Shearer, “Defining U.S. Indian Ocean Strategy”, The Washington Quarterly, Vol.35, No.2, 2012, pp.177-178.
    （3）书籍格式：作者名，书名（斜体），出版社，出版年份，页码。
例如：John Ikenberry, Liberal Levitathan，The Origins, Crisis, and Transformation of the American World Order, Princeton University Press, 2011, p.55.
    （4）网站资料：作者名：标题（加引号），文献来源（正体），文献发布时间，网址。

[http://www.pacificjournal.com.cn/CN/column/column41.shtml](url)

**Comment by zepinglee** [comment]
具体有哪些格式的差异？最好将对应文献导出为 CSL-JSON 格式，再压缩为 `.zip` 发上来。

根据 <https://zotero-chinese.com/styles/pacific-journal/> 的测试文献预览，我只注意到出版地和出版年之间缺逗号：“北京大学出版社2012年版”。

如果差异很多的话，可以将官网的 7 篇示例文献录入 Zotero，同样导出 CSL-JSON 发上来。我可以将这些作为测试文献重制一个版本的 CSL 样式。

**Comment by vw911** [comment]
谢谢回复，不好意思，之前提问有些不明确。

中文脚注问题不大，主要是英文书籍和网站资料格式存在一些问题。

1.英文书籍不需要出版地

<img width="724" alt="image" src="https://github.com/user-attachments/assets/e92c90c2-3ead-41aa-b462-ecac6a667857">

2.网站资料“标题”和网站名之间的逗号在双引号外

<img width="709" alt="image" src="https://github.com/user-attachments/assets/d62a57df-27ba-44ed-b305-64cb216b20e1">

3.英文网站资料脚注的“文献来源”要求是正体，而不是斜体，最后不需要添加网站访问时间。

因为《太平洋学报》的论文很多是最新时事热点，所以需要引用到很多新闻网站，所以网站资料的引文格式比较重要。

谢谢！

**Comment by zepinglee** [comment]
已重制，见 <https://zotero-chinese.com/styles/pacific-journal/>。

测试文献的结果差异见 <https://github.com/zotero-chinese/styles/commit/b80dcbc71241f059d0fab52fcadc0e9c3a3f0c14>。

**Comment by vw911** [comment]
谢谢大佬！
