### ISSUE TITLE
关于重制《中国社会科学》《世界经济与政治》问题的疑问

### ISSUE THREAD

**Issue by zepinglee** [EdwardSaidZhou/CSL-Chinese-IR-CSSCI-Journals#5]
我刚刚注意到新增了这么一段描述：

https://github.com/EdwardSaidZhou/CSL-Chinese-IR-CSSCI-Journals/blob/62858d46c2fb4849e1b1ff0b8950a7930bd18e77/README.md?plain=1#L37-L38

这两个问题有没有测试文献（导出为 CSL-JSON 格式）用于 debug？

《中国社会科学》的格式要求：

> 责任方式为著时，“著”可省略，其他责任方式不可省略。

而且其中的示例文献绝大部分是省略“著”的。

**Comment by EdwardSaidZhou** [comment]
> 我刚刚注意到新增了这么一段描述：
> 
> https://github.com/EdwardSaidZhou/CSL-Chinese-IR-CSSCI-Journals/blob/62858d46c2fb4849e1b1ff0b8950a7930bd18e77/README.md?plain=1#L37-L38
> 
> 这两个问题有没有测试文献（导出为 CSL-JSON 格式）用于 debug？
> 
> 《中国社会科学》的格式要求：
> 
> > 责任方式为著时，“著”可省略，其他责任方式不可省略。
> 
> 而且其中的示例文献绝大部分是省略“著”的。

目前我是无意间翻到一本中文译著，译著的责任者是“编者”，这样发现的，已经放入中国社会科学群组测试样式。
另一个问题仅发生在《世经政》这本期刊，注释样式是要“著”的，debug案例参见中国社会科学群组中的《中国人留学日本史》。

**Comment by zepinglee** [comment]
这两篇测试文献应该都是《世经政》样式的问题：

<https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/5904832de93d728aec7b3159fac1e7803de0cf0f#diff-8568236edd98c205b984deaaf322641fe8448b4d71679e959b09a68c5db1c2e0>

跟《中国社会科学》无关：

<https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/5904832de93d728aec7b3159fac1e7803de0cf0f#diff-39636f2e2535244afa4b5577815f9c16cd85fc36b1009ff283a44b1ffa16ae63>

[e205db4](https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/e205db4e780abe92a558e53a8c9c61d719b4e4f4) 中修复了这个问题：

<https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl/commit/e205db4e780abe92a558e53a8c9c61d719b4e4f4#diff-6a4aa01d8b822962ec14d221f281c6986e9e2b3d44b1a3fc5c82851c1f92c01a>

另外，英文译著文献的作者需要加“author”或者对应缩写吗？

**Comment by EdwardSaidZhou** [comment]
> 

英文译著还未看到这种说法

**Comment by zepinglee** [comment]
以后有问题的话，最好发 issue 反馈，我会尽快修改。
