### ISSUE TITLE
《世界经济与政治》网页引文格式问题

### ISSUE THREAD

**Issue by vw911** [EdwardSaidZhou/CSL-Chinese-IR-CSSCI-Journals#9]
<img width="584" alt="image" src="https://github.com/EdwardSaidZhou/CSL-Chinese-IR-CSSCI-Journals/assets/144692196/397487ec-c576-469b-a2c8-83839ddb2596">

大佬您好，
根据世经政官方注释体例，网页访问时间后面应该是中文句号，但您制作的Zotero格式英文网页访问时间后面是英文句号，希望能够修正一下，谢谢。
<img width="652" alt="image" src="https://github.com/EdwardSaidZhou/CSL-Chinese-IR-CSSCI-Journals/assets/144692196/7d321407-8c04-4918-8bfe-33e9cf0b74a2">

**Comment by EdwardSaidZhou** [comment]
您好，目前这个问题暂时还没有想出来解决方案，因为这个句号是对应英文参考文献所有类型末尾的句号，单独辟出在线资源使用中文句号结尾还无办法，当前的折中办法是，全文写作完成后，使用全局替换“日.”为“日。” 谢谢

**Comment by zepinglee** [comment]
确实需要中文标点吗？我一直以为这是示例文献搞错了。

实现倒是可以实现，只是这样格式不一致略麻烦些。

**Comment by vw911** [comment]
> 您好，目前这个问题暂时还没有想出来解决方案，因为这个句号是对应英文参考文献所有类型末尾的句号，单独辟出在线资源使用中文句号结尾还无办法，当前的折中办法是，全文写作完成后，使用全局替换“日.”为“日。” 谢谢

谢谢！
